### ISSUE TITLE
Recommended release process?

### ISSUE THREAD

**Issue by jenniferplusplus** [kubecfg/kubit#483]
@mkmik I know you have some github actions configured to manage creating new releases, but it's not obvious to me how we would trigger those normally. Or if that's even the correct process.

Can you share some guidance on how I should do that in the future?

**Comment by mkmik** [comment]
```
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, pack]
    if: startsWith(github.ref, 'refs/tags/v')
```

the GH action reacts to the creation of a tag that start swith the letter v.

so the steps are:

1. create a tag with your git client (`git tag v<number>`)
2. push the tag with your git client
3. wait for GH to react and create a release

IIRC @jdockerty did that a few times
